version: '3.3'
services:
  redbot:
    container_name: 'redbot'
    image: 'guidone/redbot'
    ports:
      - '1880:1880'
      - '1943:1943'
      - '1942:1942'
    environment:
      REDBOT_ENABLE_MISSION_CONTROL: true
      NODE_RED_ENABLE_PROJECTS: ${NODE_RED_ENABLE_PROJECTS}
      NODE_RED_ENABLE_TOURS: false
      DEV: ${DEVELOPMENT_MODE}
    volumes:
      - type: bind
        source: ${REDBOT_DIR}/nodes
        target: /usr/src/node-red/node_modules/node-red-contrib-chatbot/nodes
      - type: bind
        source: ${REDBOT_DIR}/mc_nodes
        target: /usr/src/node-red/node_modules/node-red-contrib-chatbot/mc_nodes
      - type: bind
        source: ${REDBOT_DIR}/lib
        target: /usr/src/node-red/node_modules/node-red-contrib-chatbot/lib
      - type: bind
        source: ${REDBOT_DIR}/bin
        target: /usr/src/node-red/node_modules/node-red-contrib-chatbot/bin
      - type: bind
        source: ${DATA_DIR}
        target: /data
  redbot-assets:
    container_name: 'redbot-assets'
    build:
      dockerfile: Dockerfile-webpack
      context: .
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: ${REDBOT_DIR}/src
        target: /tmp/src
      - type: bind
        source: ${REDBOT_DIR}/webpack
        target: /tmp/webpack
      - type: bind
        source: ${REDBOT_DIR}/core
        target: /tmp/core
      - type: bind
        source: ${REDBOT_DIR}/mc_plugins
        target: /tmp/mc_plugins
